//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynamicresources.app.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dynamicresources.app.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark theme ähnelt.
        /// </summary>
        internal static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_ContinueButtonLabel {
            get {
                return ResourceManager.GetString("DynamicResourcePage_ContinueButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset preferences ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_ResetPreferences {
            get {
                return ResourceManager.GetString("DynamicResourcePage_ResetPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to delete all preferences. ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_ResetPreferencesAlert {
            get {
                return ResourceManager.GetString("DynamicResourcePage_ResetPreferencesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set font size ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_SetFontSize {
            get {
                return ResourceManager.GetString("DynamicResourcePage_SetFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle light/dark theme ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_ToggleLightDarkTheme {
            get {
                return ResourceManager.GetString("DynamicResourcePage_ToggleLightDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle locale ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_ToggleLocale {
            get {
                return ResourceManager.GetString("DynamicResourcePage_ToggleLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to .NET MAUI! ähnelt.
        /// </summary>
        internal static string DynamicResourcePage_Welcome {
            get {
                return ResourceManager.GetString("DynamicResourcePage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual font size is {0}... ähnelt.
        /// </summary>
        internal static string FontSizePopup_ActualFontSizeText {
            get {
                return ResourceManager.GetString("FontSizePopup_ActualFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light theme ähnelt.
        /// </summary>
        internal static string LightThemeLabel {
            get {
                return ResourceManager.GetString("LightThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        internal static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
    }
}
