//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// XmlSchemaClassGenerator.Console -cn -n Prins -tnsf testdata_tns.txt testdata.xsd
namespace Prins
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("prins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("prins", Namespace="")]
    public partial class Prins
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("product", Form=XmlSchemaForm.Unqualified)]
        public Product Product { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("version")]
        public byte Version { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("created")]
        public string Created { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Product", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Product
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerAID", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("identification", Form=XmlSchemaForm.Unqualified)]
        public string Identification { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brand", Form=XmlSchemaForm.Unqualified)]
        public ProductBrand Brand { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("actualisationDate", Form=XmlSchemaForm.Unqualified)]
        public string ActualisationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("updateDate", Form=XmlSchemaForm.Unqualified)]
        public string UpdateDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("expirationDate", Form=XmlSchemaForm.Unqualified)]
        public string ExpirationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euFoodInfoCompliant", Form=XmlSchemaForm.Unqualified)]
        public byte EuFoodInfoCompliant { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isReducedInfo", Form=XmlSchemaForm.Unqualified)]
        public byte IsReducedInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brandImageId", Form=XmlSchemaForm.Unqualified)]
        public uint BrandImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCategory", Form=XmlSchemaForm.Unqualified)]
        public ProductCategory ProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productSubCategory", Form=XmlSchemaForm.Unqualified)]
        public ProductSubCategory ProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public ulong Gtin { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsAID", Form=XmlSchemaForm.Unqualified)]
        public string BlsAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsName", Form=XmlSchemaForm.Unqualified)]
        public string BlsName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientReferenceUnit", Form=XmlSchemaForm.Unqualified)]
        public string NutrientReferenceUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionSize", Form=XmlSchemaForm.Unqualified)]
        public byte PortionSize { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("usedBlsNutrients", Form=XmlSchemaForm.Unqualified)]
        public byte UsedBlsNutrients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productId", Form=XmlSchemaForm.Unqualified)]
        public uint ProductId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageType", Form=XmlSchemaForm.Unqualified)]
        public ProductStorageType StorageType { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("minShelfLife", Form=XmlSchemaForm.Unqualified)]
        public string MinShelfLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("remainingLife", Form=XmlSchemaForm.Unqualified)]
        public string RemainingLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isDirectDistribution", Form=XmlSchemaForm.Unqualified)]
        public byte IsDirectDistribution { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isSpecializedWholesaleTrade", Form=XmlSchemaForm.Unqualified)]
        public byte IsSpecializedWholesaleTrade { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isOnlineShopping", Form=XmlSchemaForm.Unqualified)]
        public byte IsOnlineShopping { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isCashnCarry", Form=XmlSchemaForm.Unqualified)]
        public byte IsCashnCarry { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductCategory", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductSubCategory", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("infoURL", Form=XmlSchemaForm.Unqualified)]
        public string InfoUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("servingImgId", Form=XmlSchemaForm.Unqualified)]
        public uint ServingImgId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPackEAN", Form=XmlSchemaForm.Unqualified)]
        public ulong UnitPackEan { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("singleUnitsPerTradingUnit", Form=XmlSchemaForm.Unqualified)]
        public byte SingleUnitsPerTradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("creationDate", Form=XmlSchemaForm.Unqualified)]
        public string CreationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("preparationInfo", Form=XmlSchemaForm.Unqualified)]
        public ProductPreparationInfo PreparationInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gvoDeclaration", Form=XmlSchemaForm.Unqualified)]
        public ProductGvoDeclaration GvoDeclaration { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation", Form=XmlSchemaForm.Unqualified)]
        public ProductNutrientAnnotation NutrientAnnotation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPack", Form=XmlSchemaForm.Unqualified)]
        public ProductUnitPack UnitPack { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tradingUnit", Form=XmlSchemaForm.Unqualified)]
        public ProductTradingUnit TradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("palette", Form=XmlSchemaForm.Unqualified)]
        public ProductPalette Palette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("commonInfo", Form=XmlSchemaForm.Unqualified)]
        public ProductCommonInfo CommonInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ingredients", Form=XmlSchemaForm.Unqualified)]
        public Ingredients Ingredients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageInstruction", Form=XmlSchemaForm.Unqualified)]
        public ProductStorageInstruction StorageInstruction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("techData", Form=XmlSchemaForm.Unqualified)]
        public ProductTechData TechData { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dataProducer", Form=XmlSchemaForm.Unqualified)]
        public ProductDataProducer DataProducer { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturer", Form=XmlSchemaForm.Unqualified)]
        public ProductManufacturer Manufacturer { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<Allergen> _allergens;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<Allergen> Allergens
        {
            get
            {
                return _allergens;
            }
            private set
            {
                _allergens = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Product" /> class.</para>
        /// </summary>
        public Product()
        {
            this._allergens = new Collection<Allergen>();
            this._additiveLabels = new Collection<AdditiveLabel>();
            this._additives = new Collection<Additive>();
            this._additionalProductInfos = new Collection<ProductInfo>();
            this._userSpecificInfos = new Collection<ProductUserSpecificInfo>();
            this._dietTypes = new Collection<DietType>();
            this._allergens2 = new Collection<Allergen2>();
            this._productCertifications = new Collection<ProductCertificationsProductCertification>();
            this._gtins = new Collection<ulong>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrients", Form=XmlSchemaForm.Unqualified)]
        public ProductNutrients Nutrients { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<AdditiveLabel> _additiveLabels;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additiveLabels", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("additiveLabel", Form=XmlSchemaForm.Unqualified)]
        public Collection<AdditiveLabel> AdditiveLabels
        {
            get
            {
                return _additiveLabels;
            }
            private set
            {
                _additiveLabels = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<Additive> _additives;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additives", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("additive", Form=XmlSchemaForm.Unqualified)]
        public Collection<Additive> Additives
        {
            get
            {
                return _additives;
            }
            private set
            {
                _additives = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ProductInfo> _additionalProductInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additionalProductInfos", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("productInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductInfo> AdditionalProductInfos
        {
            get
            {
                return _additionalProductInfos;
            }
            private set
            {
                _additionalProductInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ProductUserSpecificInfo> _userSpecificInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("userSpecificInfos", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("userSpecificInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductUserSpecificInfo> UserSpecificInfos
        {
            get
            {
                return _userSpecificInfos;
            }
            private set
            {
                _userSpecificInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<DietType> _dietTypes;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("dietTypes", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public Collection<DietType> DietTypes
        {
            get
            {
                return _dietTypes;
            }
            private set
            {
                _dietTypes = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<Allergen2> _allergens2;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens2", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<Allergen2> Allergens2
        {
            get
            {
                return _allergens2;
            }
            private set
            {
                _allergens2 = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ProductCertificationsProductCertification> _productCertifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("productCertifications", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("productCertification", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductCertificationsProductCertification> ProductCertifications
        {
            get
            {
                return _productCertifications;
            }
            private set
            {
                _productCertifications = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtins;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("gtins", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public Collection<ulong> Gtins
        {
            get
            {
                return _gtins;
            }
            private set
            {
                _gtins = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierData", Form=XmlSchemaForm.Unqualified)]
        public ProductSupplierData SupplierData { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductBrand", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductBrand
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductSubCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductSubCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductStorageType", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductStorageType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductPreparationInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductPreparationInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductGvoDeclaration", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductGvoDeclaration
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductNutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductNutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductUnitPack", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductUnitPack
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo", Form=XmlSchemaForm.Unqualified)]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight", Form=XmlSchemaForm.Unqualified)]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight", Form=XmlSchemaForm.Unqualified)]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue", Form=XmlSchemaForm.Unqualified)]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductTradingUnit", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductTradingUnit
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo", Form=XmlSchemaForm.Unqualified)]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight", Form=XmlSchemaForm.Unqualified)]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight", Form=XmlSchemaForm.Unqualified)]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue", Form=XmlSchemaForm.Unqualified)]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductPalette", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductPalette
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("handling", Form=XmlSchemaForm.Unqualified)]
        public string Handling { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tiersPerPalette", Form=XmlSchemaForm.Unqualified)]
        public byte TiersPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerPalette", Form=XmlSchemaForm.Unqualified)]
        public byte UnitsPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerTier", Form=XmlSchemaForm.Unqualified)]
        public byte UnitsPerTier { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("totalWeightKG", Form=XmlSchemaForm.Unqualified)]
        public string TotalWeightKg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductCommonInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductCommonInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Ingredients", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Ingredients
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductStorageInstruction", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductStorageInstruction
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductTechData", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductTechData
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductDataProducer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductDataProducer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName", Form=XmlSchemaForm.Unqualified)]
        public string ProducerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName2", Form=XmlSchemaForm.Unqualified)]
        public string ProducerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL", Form=XmlSchemaForm.Unqualified)]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerId", Form=XmlSchemaForm.Unqualified)]
        public ushort ProducerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname", Form=XmlSchemaForm.Unqualified)]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName", Form=XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation", Form=XmlSchemaForm.Unqualified)]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction", Form=XmlSchemaForm.Unqualified)]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address", Form=XmlSchemaForm.Unqualified)]
        public ProductDataProducerAddress Address { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductDataProducerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductDataProducerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode", Form=XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city", Form=XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox", Form=XmlSchemaForm.Unqualified)]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode", Form=XmlSchemaForm.Unqualified)]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street", Form=XmlSchemaForm.Unqualified)]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email", Form=XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax", Form=XmlSchemaForm.Unqualified)]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone", Form=XmlSchemaForm.Unqualified)]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www", Form=XmlSchemaForm.Unqualified)]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductManufacturer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductManufacturer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName2", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerShortName", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL", Form=XmlSchemaForm.Unqualified)]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerId", Form=XmlSchemaForm.Unqualified)]
        public ushort ManufacturerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname", Form=XmlSchemaForm.Unqualified)]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName", Form=XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation", Form=XmlSchemaForm.Unqualified)]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction", Form=XmlSchemaForm.Unqualified)]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address", Form=XmlSchemaForm.Unqualified)]
        public ProductManufacturerAddress Address { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ProductManufacturerCertificationsCertification> _certifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("certifications", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("certification", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductManufacturerCertificationsCertification> Certifications
        {
            get
            {
                return _certifications;
            }
            private set
            {
                _certifications = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductManufacturer" /> class.</para>
        /// </summary>
        public ProductManufacturer()
        {
            this._certifications = new Collection<ProductManufacturerCertificationsCertification>();
            this._glns = new Collection<uint>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _glns;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("glns", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("gln", Form=XmlSchemaForm.Unqualified)]
        public Collection<uint> Glns
        {
            get
            {
                return _glns;
            }
            private set
            {
                _glns = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductManufacturerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductManufacturerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode", Form=XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city", Form=XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox", Form=XmlSchemaForm.Unqualified)]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode", Form=XmlSchemaForm.Unqualified)]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street", Form=XmlSchemaForm.Unqualified)]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email", Form=XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax", Form=XmlSchemaForm.Unqualified)]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone", Form=XmlSchemaForm.Unqualified)]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www", Form=XmlSchemaForm.Unqualified)]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductManufacturerCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductManufacturerCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ProductManufacturerCertificationsCertification> _certification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("certification", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductManufacturerCertificationsCertification> Certification
        {
            get
            {
                return _certification;
            }
            private set
            {
                _certification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductManufacturerCertifications" /> class.</para>
        /// </summary>
        public ProductManufacturerCertifications()
        {
            this._certification = new Collection<ProductManufacturerCertificationsCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductManufacturerCertificationsCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductManufacturerCertificationsCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group", Form=XmlSchemaForm.Unqualified)]
        public string Group { get; set; }
        
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductManufacturerGlns", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductManufacturerGlns
    {
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _gln;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gln", Form=XmlSchemaForm.Unqualified)]
        public Collection<uint> Gln
        {
            get
            {
                return _gln;
            }
            private set
            {
                _gln = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductManufacturerGlns" /> class.</para>
        /// </summary>
        public ProductManufacturerGlns()
        {
            this._gln = new Collection<uint>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductAllergens", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductAllergens
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Allergen> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<Allergen> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductAllergens" /> class.</para>
        /// </summary>
        public ProductAllergens()
        {
            this._allergen = new Collection<Allergen>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Allergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Allergen
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag", Form=XmlSchemaForm.Unqualified)]
        public sbyte Flag { get; set; }
        
        [XmlElementAttribute("info", Form=XmlSchemaForm.Unqualified)]
        public string Info { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("remark", Form=XmlSchemaForm.Unqualified)]
        public string Remark { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductNutrients", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductNutrients
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Nutrient> _nutrient;
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrient", Form=XmlSchemaForm.Unqualified)]
        public Collection<Nutrient> Nutrient
        {
            get
            {
                return _nutrient;
            }
            private set
            {
                _nutrient = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductNutrients" /> class.</para>
        /// </summary>
        public ProductNutrients()
        {
            this._nutrient = new Collection<Nutrient>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation", Form=XmlSchemaForm.Unqualified)]
        public NutrientAnnotation NutrientAnnotation { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Nutrient", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Nutrient
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("code", Form=XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euName", Form=XmlSchemaForm.Unqualified)]
        public string EuName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unit", Form=XmlSchemaForm.Unqualified)]
        public string Unit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("value", Form=XmlSchemaForm.Unqualified)]
        public decimal Value { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("rda", Form=XmlSchemaForm.Unqualified)]
        public ushort Rda { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Rda property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaSpecified { get; set; }
        
        [XmlElementAttribute("rdaPercentage", Form=XmlSchemaForm.Unqualified)]
        public decimal RdaPercentage { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RdaPercentage property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaPercentageSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionValue", Form=XmlSchemaForm.Unqualified)]
        public decimal PortionValue { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("NutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class NutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductAdditiveLabels", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductAdditiveLabels
    {
        
        [XmlIgnoreAttribute()]
        private Collection<AdditiveLabel> _additiveLabel;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveLabel", Form=XmlSchemaForm.Unqualified)]
        public Collection<AdditiveLabel> AdditiveLabel
        {
            get
            {
                return _additiveLabel;
            }
            private set
            {
                _additiveLabel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductAdditiveLabels" /> class.</para>
        /// </summary>
        public ProductAdditiveLabels()
        {
            this._additiveLabel = new Collection<AdditiveLabel>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AdditiveLabel", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class AdditiveLabel
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductAdditives", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductAdditives
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Additive> _additive;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additive", Form=XmlSchemaForm.Unqualified)]
        public Collection<Additive> Additive
        {
            get
            {
                return _additive;
            }
            private set
            {
                _additive = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductAdditives" /> class.</para>
        /// </summary>
        public ProductAdditives()
        {
            this._additive = new Collection<Additive>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Additive", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Additive
    {
        
        [XmlElementAttribute("additiveClass", Form=XmlSchemaForm.Unqualified)]
        public AdditiveAdditiveClass AdditiveClass { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveName", Form=XmlSchemaForm.Unqualified)]
        public string AdditiveName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveNumber", Form=XmlSchemaForm.Unqualified)]
        public string AdditiveNumber { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AdditiveAdditiveClass", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class AdditiveAdditiveClass
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductAdditionalProductInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductAdditionalProductInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ProductInfo> _productInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductInfo> ProductInfo
        {
            get
            {
                return _productInfo;
            }
            private set
            {
                _productInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductAdditionalProductInfos" /> class.</para>
        /// </summary>
        public ProductAdditionalProductInfos()
        {
            this._productInfo = new Collection<ProductInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [XmlElementAttribute("info", Form=XmlSchemaForm.Unqualified)]
        public string Info { get; set; }
        
        [XmlElementAttribute("comment", Form=XmlSchemaForm.Unqualified)]
        public string Comment { get; set; }
        
        [XmlElementAttribute("seq", Form=XmlSchemaForm.Unqualified)]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public byte Type { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TypeSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductUserSpecificInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductUserSpecificInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ProductUserSpecificInfo> _userSpecificInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("userSpecificInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductUserSpecificInfo> UserSpecificInfo
        {
            get
            {
                return _userSpecificInfo;
            }
            private set
            {
                _userSpecificInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductUserSpecificInfos" /> class.</para>
        /// </summary>
        public ProductUserSpecificInfos()
        {
            this._userSpecificInfo = new Collection<ProductUserSpecificInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductUserSpecificInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductUserSpecificInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public byte Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("header", Form=XmlSchemaForm.Unqualified)]
        public string Header { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("seq", Form=XmlSchemaForm.Unqualified)]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductDietTypes", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductDietTypes
    {
        
        [XmlIgnoreAttribute()]
        private Collection<DietType> _dietType;
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public Collection<DietType> DietType
        {
            get
            {
                return _dietType;
            }
            private set
            {
                _dietType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductDietTypes" /> class.</para>
        /// </summary>
        public ProductDietTypes()
        {
            this._dietType = new Collection<DietType>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("DietType", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class DietType
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public string DietTypeProperty { get; set; }
        
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductAllergens2", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductAllergens2
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Allergen2> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<Allergen2> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductAllergens2" /> class.</para>
        /// </summary>
        public ProductAllergens2()
        {
            this._allergen = new Collection<Allergen2>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Allergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Allergen2
    {
        
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag", Form=XmlSchemaForm.Unqualified)]
        public byte Flag { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ProductCertificationsProductCertification> _productCertification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCertification", Form=XmlSchemaForm.Unqualified)]
        public Collection<ProductCertificationsProductCertification> ProductCertification
        {
            get
            {
                return _productCertification;
            }
            private set
            {
                _productCertification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductCertifications" /> class.</para>
        /// </summary>
        public ProductCertifications()
        {
            this._productCertification = new Collection<ProductCertificationsProductCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductCertificationsProductCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductCertificationsProductCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group", Form=XmlSchemaForm.Unqualified)]
        public string Group { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductGtins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductGtins
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtin;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public Collection<ulong> Gtin
        {
            get
            {
                return _gtin;
            }
            private set
            {
                _gtin = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductGtins" /> class.</para>
        /// </summary>
        public ProductGtins()
        {
            this._gtin = new Collection<ulong>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProductSupplierData", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ProductSupplierData
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID", Form=XmlSchemaForm.Unqualified)]
        public ushort SupplierAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID2", Form=XmlSchemaForm.Unqualified)]
        public string SupplierAid2 { get; set; }
    }
}
