//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// XmlSchemaClassGenerator.Console -cn -n Prins testdata.xsd
namespace Prins
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("prins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("prins", Namespace="")]
    public partial class Prins
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("product")]
        public PrinsProduct Product { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("version")]
        public byte Version { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("created")]
        public string Created { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProduct", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProduct
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerAID")]
        public string ManufacturerAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("identification")]
        public string Identification { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brand")]
        public PrinsProductBrand Brand { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("actualisationDate")]
        public string ActualisationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("updateDate")]
        public string UpdateDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("expirationDate")]
        public string ExpirationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euFoodInfoCompliant")]
        public byte EuFoodInfoCompliant { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isReducedInfo")]
        public byte IsReducedInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brandImageId")]
        public uint BrandImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCategory")]
        public PrinsProductProductCategory ProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productSubCategory")]
        public PrinsProductProductSubCategory ProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin")]
        public ulong Gtin { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsAID")]
        public string BlsAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsName")]
        public string BlsName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientReferenceUnit")]
        public string NutrientReferenceUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionSize")]
        public byte PortionSize { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("usedBlsNutrients")]
        public byte UsedBlsNutrients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productId")]
        public uint ProductId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageType")]
        public PrinsProductStorageType StorageType { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("minShelfLife")]
        public string MinShelfLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("remainingLife")]
        public string RemainingLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isDirectDistribution")]
        public byte IsDirectDistribution { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isSpecializedWholesaleTrade")]
        public byte IsSpecializedWholesaleTrade { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isOnlineShopping")]
        public byte IsOnlineShopping { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isCashnCarry")]
        public byte IsCashnCarry { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductCategory")]
        public string ManufacturerProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductSubCategory")]
        public string ManufacturerProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("infoURL")]
        public string InfoUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("servingImgId")]
        public uint ServingImgId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPackEAN")]
        public ulong UnitPackEan { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("singleUnitsPerTradingUnit")]
        public byte SingleUnitsPerTradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("creationDate")]
        public string CreationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("preparationInfo")]
        public PrinsProductPreparationInfo PreparationInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gvoDeclaration")]
        public PrinsProductGvoDeclaration GvoDeclaration { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation")]
        public PrinsProductNutrientAnnotation NutrientAnnotation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPack")]
        public PrinsProductUnitPack UnitPack { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tradingUnit")]
        public PrinsProductTradingUnit TradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("palette")]
        public PrinsProductPalette Palette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("commonInfo")]
        public PrinsProductCommonInfo CommonInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ingredients")]
        public PrinsProductIngredients Ingredients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageInstruction")]
        public PrinsProductStorageInstruction StorageInstruction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("techData")]
        public PrinsProductTechData TechData { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dataProducer")]
        public PrinsProductDataProducer DataProducer { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturer")]
        public PrinsProductManufacturer Manufacturer { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergensAllergen> _allergens;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens")]
        [XmlArrayItemAttribute("allergen")]
        public Collection<PrinsProductAllergensAllergen> Allergens
        {
            get
            {
                return _allergens;
            }
            private set
            {
                _allergens = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProduct" /> class.</para>
        /// </summary>
        public PrinsProduct()
        {
            this._allergens = new Collection<PrinsProductAllergensAllergen>();
            this._additiveLabels = new Collection<PrinsProductAdditiveLabelsAdditiveLabel>();
            this._additives = new Collection<PrinsProductAdditivesAdditive>();
            this._additionalProductInfos = new Collection<PrinsProductAdditionalProductInfosProductInfo>();
            this._userSpecificInfos = new Collection<PrinsProductUserSpecificInfosUserSpecificInfo>();
            this._dietTypes = new Collection<PrinsProductDietTypesDietType>();
            this._allergens2 = new Collection<PrinsProductAllergens2Allergen>();
            this._productCertifications = new Collection<PrinsProductProductCertificationsProductCertification>();
            this._gtins = new Collection<ulong>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrients")]
        public PrinsProductNutrients Nutrients { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditiveLabelsAdditiveLabel> _additiveLabels;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additiveLabels")]
        [XmlArrayItemAttribute("additiveLabel")]
        public Collection<PrinsProductAdditiveLabelsAdditiveLabel> AdditiveLabels
        {
            get
            {
                return _additiveLabels;
            }
            private set
            {
                _additiveLabels = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditivesAdditive> _additives;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additives")]
        [XmlArrayItemAttribute("additive")]
        public Collection<PrinsProductAdditivesAdditive> Additives
        {
            get
            {
                return _additives;
            }
            private set
            {
                _additives = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditionalProductInfosProductInfo> _additionalProductInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additionalProductInfos")]
        [XmlArrayItemAttribute("productInfo")]
        public Collection<PrinsProductAdditionalProductInfosProductInfo> AdditionalProductInfos
        {
            get
            {
                return _additionalProductInfos;
            }
            private set
            {
                _additionalProductInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductUserSpecificInfosUserSpecificInfo> _userSpecificInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("userSpecificInfos")]
        [XmlArrayItemAttribute("userSpecificInfo")]
        public Collection<PrinsProductUserSpecificInfosUserSpecificInfo> UserSpecificInfos
        {
            get
            {
                return _userSpecificInfos;
            }
            private set
            {
                _userSpecificInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductDietTypesDietType> _dietTypes;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("dietTypes")]
        [XmlArrayItemAttribute("dietType")]
        public Collection<PrinsProductDietTypesDietType> DietTypes
        {
            get
            {
                return _dietTypes;
            }
            private set
            {
                _dietTypes = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergens2Allergen> _allergens2;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens2")]
        [XmlArrayItemAttribute("allergen")]
        public Collection<PrinsProductAllergens2Allergen> Allergens2
        {
            get
            {
                return _allergens2;
            }
            private set
            {
                _allergens2 = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductProductCertificationsProductCertification> _productCertifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("productCertifications")]
        [XmlArrayItemAttribute("productCertification")]
        public Collection<PrinsProductProductCertificationsProductCertification> ProductCertifications
        {
            get
            {
                return _productCertifications;
            }
            private set
            {
                _productCertifications = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtins;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("gtins")]
        [XmlArrayItemAttribute("gtin")]
        public Collection<ulong> Gtins
        {
            get
            {
                return _gtins;
            }
            private set
            {
                _gtins = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierData")]
        public PrinsProductSupplierData SupplierData { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductBrand", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductBrand
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductSubCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductSubCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductStorageType", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductStorageType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductPreparationInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductPreparationInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductGvoDeclaration", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductGvoDeclaration
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUnitPack", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUnitPack
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo")]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension")]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight")]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox")]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit")]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue")]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight")]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox")]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit")]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue")]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight")]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit")]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue")]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight")]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue")]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductTradingUnit", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductTradingUnit
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo")]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension")]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type")]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight")]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox")]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit")]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue")]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight")]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox")]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit")]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue")]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight")]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit")]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue")]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight")]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue")]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductPalette", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductPalette
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension")]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("handling")]
        public string Handling { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tiersPerPalette")]
        public byte TiersPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type")]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerPalette")]
        public byte UnitsPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerTier")]
        public byte UnitsPerTier { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("totalWeightKG")]
        public string TotalWeightKg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductCommonInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductCommonInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductIngredients", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductIngredients
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductStorageInstruction", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductStorageInstruction
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductTechData", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductTechData
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDataProducer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDataProducer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName")]
        public string ProducerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName2")]
        public string ProducerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName")]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL")]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerId")]
        public ushort ProducerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname")]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName")]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation")]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction")]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address")]
        public PrinsProductDataProducerAddress Address { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDataProducerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDataProducerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode")]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city")]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox")]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode")]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street")]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email")]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax")]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone")]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www")]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName")]
        public string ManufacturerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName2")]
        public string ManufacturerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerShortName")]
        public string ManufacturerShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL")]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerId")]
        public ushort ManufacturerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname")]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName")]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation")]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction")]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address")]
        public PrinsProductManufacturerAddress Address { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductManufacturerCertificationsCertification> _certifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("certifications")]
        [XmlArrayItemAttribute("certification")]
        public Collection<PrinsProductManufacturerCertificationsCertification> Certifications
        {
            get
            {
                return _certifications;
            }
            private set
            {
                _certifications = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturer" /> class.</para>
        /// </summary>
        public PrinsProductManufacturer()
        {
            this._certifications = new Collection<PrinsProductManufacturerCertificationsCertification>();
            this._glns = new Collection<uint>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _glns;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("glns")]
        [XmlArrayItemAttribute("gln")]
        public Collection<uint> Glns
        {
            get
            {
                return _glns;
            }
            private set
            {
                _glns = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode")]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city")]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox")]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode")]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street")]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email")]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax")]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone")]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www")]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductManufacturerCertificationsCertification> _certification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("certification")]
        public Collection<PrinsProductManufacturerCertificationsCertification> Certification
        {
            get
            {
                return _certification;
            }
            private set
            {
                _certification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturerCertifications" /> class.</para>
        /// </summary>
        public PrinsProductManufacturerCertifications()
        {
            this._certification = new Collection<PrinsProductManufacturerCertificationsCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerCertificationsCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerCertificationsCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group")]
        public string Group { get; set; }
        
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerGlns", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerGlns
    {
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _gln;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gln")]
        public Collection<uint> Gln
        {
            get
            {
                return _gln;
            }
            private set
            {
                _gln = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturerGlns" /> class.</para>
        /// </summary>
        public PrinsProductManufacturerGlns()
        {
            this._gln = new Collection<uint>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergensAllergen> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen")]
        public Collection<PrinsProductAllergensAllergen> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAllergens" /> class.</para>
        /// </summary>
        public PrinsProductAllergens()
        {
            this._allergen = new Collection<PrinsProductAllergensAllergen>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergensAllergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergensAllergen
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName")]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag")]
        public sbyte Flag { get; set; }
        
        [XmlElementAttribute("info")]
        public string Info { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [XmlElementAttribute("remark")]
        public string Remark { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrients", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrients
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductNutrientsNutrient> _nutrient;
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrient")]
        public Collection<PrinsProductNutrientsNutrient> Nutrient
        {
            get
            {
                return _nutrient;
            }
            private set
            {
                _nutrient = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductNutrients" /> class.</para>
        /// </summary>
        public PrinsProductNutrients()
        {
            this._nutrient = new Collection<PrinsProductNutrientsNutrient>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation")]
        public PrinsProductNutrientsNutrientAnnotation NutrientAnnotation { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientsNutrient", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientsNutrient
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("code")]
        public string Code { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euName")]
        public string EuName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unit")]
        public string Unit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("value")]
        public decimal Value { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [XmlElementAttribute("rda")]
        public ushort Rda { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Rda property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaSpecified { get; set; }
        
        [XmlElementAttribute("rdaPercentage")]
        public decimal RdaPercentage { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RdaPercentage property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaPercentageSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionValue")]
        public decimal PortionValue { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientsNutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientsNutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditiveLabels", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditiveLabels
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditiveLabelsAdditiveLabel> _additiveLabel;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveLabel")]
        public Collection<PrinsProductAdditiveLabelsAdditiveLabel> AdditiveLabel
        {
            get
            {
                return _additiveLabel;
            }
            private set
            {
                _additiveLabel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditiveLabels" /> class.</para>
        /// </summary>
        public PrinsProductAdditiveLabels()
        {
            this._additiveLabel = new Collection<PrinsProductAdditiveLabelsAdditiveLabel>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditiveLabelsAdditiveLabel", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditiveLabelsAdditiveLabel
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditives", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditives
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditivesAdditive> _additive;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additive")]
        public Collection<PrinsProductAdditivesAdditive> Additive
        {
            get
            {
                return _additive;
            }
            private set
            {
                _additive = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditives" /> class.</para>
        /// </summary>
        public PrinsProductAdditives()
        {
            this._additive = new Collection<PrinsProductAdditivesAdditive>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditivesAdditive", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditivesAdditive
    {
        
        [XmlElementAttribute("additiveClass")]
        public PrinsProductAdditivesAdditiveAdditiveClass AdditiveClass { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveName")]
        public string AdditiveName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveNumber")]
        public string AdditiveNumber { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditivesAdditiveAdditiveClass", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditivesAdditiveAdditiveClass
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditionalProductInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditionalProductInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditionalProductInfosProductInfo> _productInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productInfo")]
        public Collection<PrinsProductAdditionalProductInfosProductInfo> ProductInfo
        {
            get
            {
                return _productInfo;
            }
            private set
            {
                _productInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditionalProductInfos" /> class.</para>
        /// </summary>
        public PrinsProductAdditionalProductInfos()
        {
            this._productInfo = new Collection<PrinsProductAdditionalProductInfosProductInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditionalProductInfosProductInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditionalProductInfosProductInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [XmlElementAttribute("info")]
        public string Info { get; set; }
        
        [XmlElementAttribute("comment")]
        public string Comment { get; set; }
        
        [XmlElementAttribute("seq")]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [XmlElementAttribute("type")]
        public byte Type { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TypeSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUserSpecificInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUserSpecificInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductUserSpecificInfosUserSpecificInfo> _userSpecificInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("userSpecificInfo")]
        public Collection<PrinsProductUserSpecificInfosUserSpecificInfo> UserSpecificInfo
        {
            get
            {
                return _userSpecificInfo;
            }
            private set
            {
                _userSpecificInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductUserSpecificInfos" /> class.</para>
        /// </summary>
        public PrinsProductUserSpecificInfos()
        {
            this._userSpecificInfo = new Collection<PrinsProductUserSpecificInfosUserSpecificInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUserSpecificInfosUserSpecificInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUserSpecificInfosUserSpecificInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("type")]
        public byte Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("header")]
        public string Header { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [XmlElementAttribute("seq")]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDietTypes", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDietTypes
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductDietTypesDietType> _dietType;
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType")]
        public Collection<PrinsProductDietTypesDietType> DietType
        {
            get
            {
                return _dietType;
            }
            private set
            {
                _dietType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductDietTypes" /> class.</para>
        /// </summary>
        public PrinsProductDietTypes()
        {
            this._dietType = new Collection<PrinsProductDietTypesDietType>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDietTypesDietType", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDietTypesDietType
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType")]
        public string DietType { get; set; }
        
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens2", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens2
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergens2Allergen> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen")]
        public Collection<PrinsProductAllergens2Allergen> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAllergens2" /> class.</para>
        /// </summary>
        public PrinsProductAllergens2()
        {
            this._allergen = new Collection<PrinsProductAllergens2Allergen>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens2Allergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens2Allergen
    {
        
        [XmlElementAttribute("shortName")]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag")]
        public byte Flag { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductProductCertificationsProductCertification> _productCertification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCertification")]
        public Collection<PrinsProductProductCertificationsProductCertification> ProductCertification
        {
            get
            {
                return _productCertification;
            }
            private set
            {
                _productCertification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductProductCertifications" /> class.</para>
        /// </summary>
        public PrinsProductProductCertifications()
        {
            this._productCertification = new Collection<PrinsProductProductCertificationsProductCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCertificationsProductCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCertificationsProductCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group")]
        public string Group { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId")]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductGtins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductGtins
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtin;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin")]
        public Collection<ulong> Gtin
        {
            get
            {
                return _gtin;
            }
            private set
            {
                _gtin = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductGtins" /> class.</para>
        /// </summary>
        public PrinsProductGtins()
        {
            this._gtin = new Collection<ulong>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductSupplierData", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductSupplierData
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID")]
        public ushort SupplierAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID2")]
        public string SupplierAid2 { get; set; }
    }
}
