//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// XmlSchemaClassGenerator.Console -cn -n PrinsUnqualified testdata.xsd
namespace PrinsUnqualified
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("prins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("prins", Namespace="")]
    public partial class Prins
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("product", Form=XmlSchemaForm.Unqualified)]
        public PrinsProduct Product { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("version")]
        public byte Version { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("created")]
        public string Created { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProduct", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProduct
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerAID", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("identification", Form=XmlSchemaForm.Unqualified)]
        public string Identification { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brand", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductBrand Brand { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("actualisationDate", Form=XmlSchemaForm.Unqualified)]
        public string ActualisationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("updateDate", Form=XmlSchemaForm.Unqualified)]
        public string UpdateDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("expirationDate", Form=XmlSchemaForm.Unqualified)]
        public string ExpirationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euFoodInfoCompliant", Form=XmlSchemaForm.Unqualified)]
        public byte EuFoodInfoCompliant { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isReducedInfo", Form=XmlSchemaForm.Unqualified)]
        public byte IsReducedInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("brandImageId", Form=XmlSchemaForm.Unqualified)]
        public uint BrandImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCategory", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductProductCategory ProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productSubCategory", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductProductSubCategory ProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public ulong Gtin { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsAID", Form=XmlSchemaForm.Unqualified)]
        public string BlsAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("blsName", Form=XmlSchemaForm.Unqualified)]
        public string BlsName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientReferenceUnit", Form=XmlSchemaForm.Unqualified)]
        public string NutrientReferenceUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionSize", Form=XmlSchemaForm.Unqualified)]
        public byte PortionSize { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("usedBlsNutrients", Form=XmlSchemaForm.Unqualified)]
        public byte UsedBlsNutrients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("productId", Form=XmlSchemaForm.Unqualified)]
        public uint ProductId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageType", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductStorageType StorageType { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("minShelfLife", Form=XmlSchemaForm.Unqualified)]
        public string MinShelfLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("remainingLife", Form=XmlSchemaForm.Unqualified)]
        public string RemainingLife { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isDirectDistribution", Form=XmlSchemaForm.Unqualified)]
        public byte IsDirectDistribution { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isSpecializedWholesaleTrade", Form=XmlSchemaForm.Unqualified)]
        public byte IsSpecializedWholesaleTrade { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isOnlineShopping", Form=XmlSchemaForm.Unqualified)]
        public byte IsOnlineShopping { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("isCashnCarry", Form=XmlSchemaForm.Unqualified)]
        public byte IsCashnCarry { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductCategory", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerProductCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerProductSubCategory", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerProductSubCategory { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("infoURL", Form=XmlSchemaForm.Unqualified)]
        public string InfoUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("servingImgId", Form=XmlSchemaForm.Unqualified)]
        public uint ServingImgId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPackEAN", Form=XmlSchemaForm.Unqualified)]
        public ulong UnitPackEan { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("singleUnitsPerTradingUnit", Form=XmlSchemaForm.Unqualified)]
        public byte SingleUnitsPerTradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("creationDate", Form=XmlSchemaForm.Unqualified)]
        public string CreationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("preparationInfo", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductPreparationInfo PreparationInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("gvoDeclaration", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductGvoDeclaration GvoDeclaration { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductNutrientAnnotation NutrientAnnotation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitPack", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductUnitPack UnitPack { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tradingUnit", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductTradingUnit TradingUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("palette", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductPalette Palette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("commonInfo", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductCommonInfo CommonInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ingredients", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductIngredients Ingredients { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("storageInstruction", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductStorageInstruction StorageInstruction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("techData", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductTechData TechData { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dataProducer", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductDataProducer DataProducer { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturer", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductManufacturer Manufacturer { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergensAllergen> _allergens;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAllergensAllergen> Allergens
        {
            get
            {
                return _allergens;
            }
            private set
            {
                _allergens = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProduct" /> class.</para>
        /// </summary>
        public PrinsProduct()
        {
            this._allergens = new Collection<PrinsProductAllergensAllergen>();
            this._additiveLabels = new Collection<PrinsProductAdditiveLabelsAdditiveLabel>();
            this._additives = new Collection<PrinsProductAdditivesAdditive>();
            this._additionalProductInfos = new Collection<PrinsProductAdditionalProductInfosProductInfo>();
            this._userSpecificInfos = new Collection<PrinsProductUserSpecificInfosUserSpecificInfo>();
            this._dietTypes = new Collection<PrinsProductDietTypesDietType>();
            this._allergens2 = new Collection<PrinsProductAllergens2Allergen>();
            this._productCertifications = new Collection<PrinsProductProductCertificationsProductCertification>();
            this._gtins = new Collection<ulong>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrients", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductNutrients Nutrients { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditiveLabelsAdditiveLabel> _additiveLabels;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additiveLabels", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("additiveLabel", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditiveLabelsAdditiveLabel> AdditiveLabels
        {
            get
            {
                return _additiveLabels;
            }
            private set
            {
                _additiveLabels = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditivesAdditive> _additives;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additives", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("additive", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditivesAdditive> Additives
        {
            get
            {
                return _additives;
            }
            private set
            {
                _additives = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditionalProductInfosProductInfo> _additionalProductInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("additionalProductInfos", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("productInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditionalProductInfosProductInfo> AdditionalProductInfos
        {
            get
            {
                return _additionalProductInfos;
            }
            private set
            {
                _additionalProductInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductUserSpecificInfosUserSpecificInfo> _userSpecificInfos;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("userSpecificInfos", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("userSpecificInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductUserSpecificInfosUserSpecificInfo> UserSpecificInfos
        {
            get
            {
                return _userSpecificInfos;
            }
            private set
            {
                _userSpecificInfos = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductDietTypesDietType> _dietTypes;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("dietTypes", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductDietTypesDietType> DietTypes
        {
            get
            {
                return _dietTypes;
            }
            private set
            {
                _dietTypes = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergens2Allergen> _allergens2;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("allergens2", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAllergens2Allergen> Allergens2
        {
            get
            {
                return _allergens2;
            }
            private set
            {
                _allergens2 = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductProductCertificationsProductCertification> _productCertifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("productCertifications", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("productCertification", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductProductCertificationsProductCertification> ProductCertifications
        {
            get
            {
                return _productCertifications;
            }
            private set
            {
                _productCertifications = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtins;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("gtins", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public Collection<ulong> Gtins
        {
            get
            {
                return _gtins;
            }
            private set
            {
                _gtins = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierData", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductSupplierData SupplierData { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductBrand", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductBrand
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductSubCategory", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductSubCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public sbyte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductStorageType", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductStorageType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductPreparationInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductPreparationInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductGvoDeclaration", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductGvoDeclaration
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUnitPack", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUnitPack
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo", Form=XmlSchemaForm.Unqualified)]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight", Form=XmlSchemaForm.Unqualified)]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight", Form=XmlSchemaForm.Unqualified)]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue", Form=XmlSchemaForm.Unqualified)]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductTradingUnit", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductTradingUnit
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("contentInfo", Form=XmlSchemaForm.Unqualified)]
        public string ContentInfo { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeight", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte GrossWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string GrossWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("grossWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort GrossWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeight", Form=XmlSchemaForm.Unqualified)]
        public string NetWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightApprox", Form=XmlSchemaForm.Unqualified)]
        public byte NetWeightApprox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string NetWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("netWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort NetWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeight", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightUnit", Form=XmlSchemaForm.Unqualified)]
        public string DrainWeightUnit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("drainWeightValue", Form=XmlSchemaForm.Unqualified)]
        public ushort DrainWeightValue { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeight", Form=XmlSchemaForm.Unqualified)]
        public string PackagingWeight { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("packagingWeightValue", Form=XmlSchemaForm.Unqualified)]
        public byte PackagingWeightValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductPalette", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductPalette
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dimension", Form=XmlSchemaForm.Unqualified)]
        public string Dimension { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("handling", Form=XmlSchemaForm.Unqualified)]
        public string Handling { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("tiersPerPalette", Form=XmlSchemaForm.Unqualified)]
        public byte TiersPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerPalette", Form=XmlSchemaForm.Unqualified)]
        public byte UnitsPerPalette { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unitsPerTier", Form=XmlSchemaForm.Unqualified)]
        public byte UnitsPerTier { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("totalWeightKG", Form=XmlSchemaForm.Unqualified)]
        public string TotalWeightKg { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductCommonInfo", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductCommonInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductIngredients", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductIngredients
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductStorageInstruction", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductStorageInstruction
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductTechData", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductTechData
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDataProducer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDataProducer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName", Form=XmlSchemaForm.Unqualified)]
        public string ProducerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerName2", Form=XmlSchemaForm.Unqualified)]
        public string ProducerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL", Form=XmlSchemaForm.Unqualified)]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("producerId", Form=XmlSchemaForm.Unqualified)]
        public ushort ProducerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname", Form=XmlSchemaForm.Unqualified)]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName", Form=XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation", Form=XmlSchemaForm.Unqualified)]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction", Form=XmlSchemaForm.Unqualified)]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductDataProducerAddress Address { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDataProducerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDataProducerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode", Form=XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city", Form=XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox", Form=XmlSchemaForm.Unqualified)]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode", Form=XmlSchemaForm.Unqualified)]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street", Form=XmlSchemaForm.Unqualified)]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email", Form=XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax", Form=XmlSchemaForm.Unqualified)]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone", Form=XmlSchemaForm.Unqualified)]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www", Form=XmlSchemaForm.Unqualified)]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturer", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturer
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerName2", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerName2 { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerShortName", Form=XmlSchemaForm.Unqualified)]
        public string ManufacturerShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("shopURL", Form=XmlSchemaForm.Unqualified)]
        public string ShopUrl { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("manufacturerId", Form=XmlSchemaForm.Unqualified)]
        public ushort ManufacturerId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFirstname", Form=XmlSchemaForm.Unqualified)]
        public string ContactFirstname { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactName", Form=XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactSalutation", Form=XmlSchemaForm.Unqualified)]
        public string ContactSalutation { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("contactFunction", Form=XmlSchemaForm.Unqualified)]
        public string ContactFunction { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("address", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductManufacturerAddress Address { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductManufacturerCertificationsCertification> _certifications;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("certifications", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("certification", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductManufacturerCertificationsCertification> Certifications
        {
            get
            {
                return _certifications;
            }
            private set
            {
                _certifications = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturer" /> class.</para>
        /// </summary>
        public PrinsProductManufacturer()
        {
            this._certifications = new Collection<PrinsProductManufacturerCertificationsCertification>();
            this._glns = new Collection<uint>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _glns;
        
        [RequiredAttribute()]
        [XmlArrayAttribute("glns", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("gln", Form=XmlSchemaForm.Unqualified)]
        public Collection<uint> Glns
        {
            get
            {
                return _glns;
            }
            private set
            {
                _glns = value;
            }
        }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerAddress", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerAddress
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("countryCode", Form=XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("city", Form=XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("pobox", Form=XmlSchemaForm.Unqualified)]
        public ushort Pobox { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("zipCode", Form=XmlSchemaForm.Unqualified)]
        public ushort ZipCode { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("street", Form=XmlSchemaForm.Unqualified)]
        public string Street { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("email", Form=XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("fax", Form=XmlSchemaForm.Unqualified)]
        public string Fax { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("phone", Form=XmlSchemaForm.Unqualified)]
        public string Phone { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("www", Form=XmlSchemaForm.Unqualified)]
        public string Www { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductManufacturerCertificationsCertification> _certification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("certification", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductManufacturerCertificationsCertification> Certification
        {
            get
            {
                return _certification;
            }
            private set
            {
                _certification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturerCertifications" /> class.</para>
        /// </summary>
        public PrinsProductManufacturerCertifications()
        {
            this._certification = new Collection<PrinsProductManufacturerCertificationsCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerCertificationsCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerCertificationsCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group", Form=XmlSchemaForm.Unqualified)]
        public string Group { get; set; }
        
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductManufacturerGlns", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductManufacturerGlns
    {
        
        [XmlIgnoreAttribute()]
        private Collection<uint> _gln;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gln", Form=XmlSchemaForm.Unqualified)]
        public Collection<uint> Gln
        {
            get
            {
                return _gln;
            }
            private set
            {
                _gln = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductManufacturerGlns" /> class.</para>
        /// </summary>
        public PrinsProductManufacturerGlns()
        {
            this._gln = new Collection<uint>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergensAllergen> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAllergensAllergen> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAllergens" /> class.</para>
        /// </summary>
        public PrinsProductAllergens()
        {
            this._allergen = new Collection<PrinsProductAllergensAllergen>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergensAllergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergensAllergen
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag", Form=XmlSchemaForm.Unqualified)]
        public sbyte Flag { get; set; }
        
        [XmlElementAttribute("info", Form=XmlSchemaForm.Unqualified)]
        public string Info { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("remark", Form=XmlSchemaForm.Unqualified)]
        public string Remark { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrients", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrients
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductNutrientsNutrient> _nutrient;
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrient", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductNutrientsNutrient> Nutrient
        {
            get
            {
                return _nutrient;
            }
            private set
            {
                _nutrient = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductNutrients" /> class.</para>
        /// </summary>
        public PrinsProductNutrients()
        {
            this._nutrient = new Collection<PrinsProductNutrientsNutrient>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("nutrientAnnotation", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductNutrientsNutrientAnnotation NutrientAnnotation { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientsNutrient", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientsNutrient
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("code", Form=XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("euName", Form=XmlSchemaForm.Unqualified)]
        public string EuName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("unit", Form=XmlSchemaForm.Unqualified)]
        public string Unit { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("value", Form=XmlSchemaForm.Unqualified)]
        public decimal Value { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("rda", Form=XmlSchemaForm.Unqualified)]
        public ushort Rda { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Rda property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaSpecified { get; set; }
        
        [XmlElementAttribute("rdaPercentage", Form=XmlSchemaForm.Unqualified)]
        public decimal RdaPercentage { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RdaPercentage property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RdaPercentageSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("portionValue", Form=XmlSchemaForm.Unqualified)]
        public decimal PortionValue { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductNutrientsNutrientAnnotation", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductNutrientsNutrientAnnotation
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public byte Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditiveLabels", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditiveLabels
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditiveLabelsAdditiveLabel> _additiveLabel;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveLabel", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditiveLabelsAdditiveLabel> AdditiveLabel
        {
            get
            {
                return _additiveLabel;
            }
            private set
            {
                _additiveLabel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditiveLabels" /> class.</para>
        /// </summary>
        public PrinsProductAdditiveLabels()
        {
            this._additiveLabel = new Collection<PrinsProductAdditiveLabelsAdditiveLabel>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditiveLabelsAdditiveLabel", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditiveLabelsAdditiveLabel
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditives", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditives
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditivesAdditive> _additive;
        
        [RequiredAttribute()]
        [XmlElementAttribute("additive", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditivesAdditive> Additive
        {
            get
            {
                return _additive;
            }
            private set
            {
                _additive = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditives" /> class.</para>
        /// </summary>
        public PrinsProductAdditives()
        {
            this._additive = new Collection<PrinsProductAdditivesAdditive>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditivesAdditive", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditivesAdditive
    {
        
        [XmlElementAttribute("additiveClass", Form=XmlSchemaForm.Unqualified)]
        public PrinsProductAdditivesAdditiveAdditiveClass AdditiveClass { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveName", Form=XmlSchemaForm.Unqualified)]
        public string AdditiveName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("additiveNumber", Form=XmlSchemaForm.Unqualified)]
        public string AdditiveNumber { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditivesAdditiveAdditiveClass", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditivesAdditiveAdditiveClass
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditionalProductInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditionalProductInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAdditionalProductInfosProductInfo> _productInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAdditionalProductInfosProductInfo> ProductInfo
        {
            get
            {
                return _productInfo;
            }
            private set
            {
                _productInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAdditionalProductInfos" /> class.</para>
        /// </summary>
        public PrinsProductAdditionalProductInfos()
        {
            this._productInfo = new Collection<PrinsProductAdditionalProductInfosProductInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAdditionalProductInfosProductInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAdditionalProductInfosProductInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [XmlElementAttribute("info", Form=XmlSchemaForm.Unqualified)]
        public string Info { get; set; }
        
        [XmlElementAttribute("comment", Form=XmlSchemaForm.Unqualified)]
        public string Comment { get; set; }
        
        [XmlElementAttribute("seq", Form=XmlSchemaForm.Unqualified)]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public byte Type { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Type property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TypeSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUserSpecificInfos", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUserSpecificInfos
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductUserSpecificInfosUserSpecificInfo> _userSpecificInfo;
        
        [RequiredAttribute()]
        [XmlElementAttribute("userSpecificInfo", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductUserSpecificInfosUserSpecificInfo> UserSpecificInfo
        {
            get
            {
                return _userSpecificInfo;
            }
            private set
            {
                _userSpecificInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductUserSpecificInfos" /> class.</para>
        /// </summary>
        public PrinsProductUserSpecificInfos()
        {
            this._userSpecificInfo = new Collection<PrinsProductUserSpecificInfosUserSpecificInfo>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductUserSpecificInfosUserSpecificInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductUserSpecificInfosUserSpecificInfo
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("type", Form=XmlSchemaForm.Unqualified)]
        public byte Type { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("header", Form=XmlSchemaForm.Unqualified)]
        public string Header { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [XmlElementAttribute("seq", Form=XmlSchemaForm.Unqualified)]
        public byte Seq { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SeqSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public uint Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDietTypes", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDietTypes
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductDietTypesDietType> _dietType;
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductDietTypesDietType> DietType
        {
            get
            {
                return _dietType;
            }
            private set
            {
                _dietType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductDietTypes" /> class.</para>
        /// </summary>
        public PrinsProductDietTypes()
        {
            this._dietType = new Collection<PrinsProductDietTypesDietType>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductDietTypesDietType", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductDietTypesDietType
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("dietType", Form=XmlSchemaForm.Unqualified)]
        public string DietType { get; set; }
        
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ImageIdSpecified { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens2", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens2
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductAllergens2Allergen> _allergen;
        
        [RequiredAttribute()]
        [XmlElementAttribute("allergen", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductAllergens2Allergen> Allergen
        {
            get
            {
                return _allergen;
            }
            private set
            {
                _allergen = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductAllergens2" /> class.</para>
        /// </summary>
        public PrinsProductAllergens2()
        {
            this._allergen = new Collection<PrinsProductAllergens2Allergen>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductAllergens2Allergen", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductAllergens2Allergen
    {
        
        [XmlElementAttribute("shortName", Form=XmlSchemaForm.Unqualified)]
        public string ShortName { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("name", Form=XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("flag", Form=XmlSchemaForm.Unqualified)]
        public byte Flag { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCertifications", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCertifications
    {
        
        [XmlIgnoreAttribute()]
        private Collection<PrinsProductProductCertificationsProductCertification> _productCertification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("productCertification", Form=XmlSchemaForm.Unqualified)]
        public Collection<PrinsProductProductCertificationsProductCertification> ProductCertification
        {
            get
            {
                return _productCertification;
            }
            private set
            {
                _productCertification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductProductCertifications" /> class.</para>
        /// </summary>
        public PrinsProductProductCertifications()
        {
            this._productCertification = new Collection<PrinsProductProductCertificationsProductCertification>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductProductCertificationsProductCertification", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductProductCertificationsProductCertification
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("text", Form=XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("group", Form=XmlSchemaForm.Unqualified)]
        public string Group { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("imageId", Form=XmlSchemaForm.Unqualified)]
        public uint ImageId { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("id")]
        public ushort Id { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductGtins", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductGtins
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ulong> _gtin;
        
        [RequiredAttribute()]
        [XmlElementAttribute("gtin", Form=XmlSchemaForm.Unqualified)]
        public Collection<ulong> Gtin
        {
            get
            {
                return _gtin;
            }
            private set
            {
                _gtin = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrinsProductGtins" /> class.</para>
        /// </summary>
        public PrinsProductGtins()
        {
            this._gtin = new Collection<ulong>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PrinsProductSupplierData", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PrinsProductSupplierData
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID", Form=XmlSchemaForm.Unqualified)]
        public ushort SupplierAid { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("supplierAID2", Form=XmlSchemaForm.Unqualified)]
        public string SupplierAid2 { get; set; }
    }
}
