//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// XmlSchemaClassGenerator.Console -cn -n Prins testdata_freeformatter.xsd
namespace Prins;

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;


[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("address", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("address", Namespace="")]
public partial class Address
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("countryCode")]
    public string CountryCode { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("city")]
    public string City { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("pobox")]
    public short Pobox { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("zipCode")]
    public short ZipCode { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("street")]
    public string Street { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("email")]
    public string Email { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("fax")]
    public string Fax { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("phone")]
    public string Phone { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("www")]
    public string Www { get; set; }
    
    [XmlAttributeAttribute("id")]
    public int Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("certification", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("certification", Namespace="")]
public partial class Certification
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("text")]
    public string Text { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("group")]
    public string Group { get; set; }
    
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool ImageIdSpecified { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("certifications", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("certifications", Namespace="")]
public partial class Certifications
{
    
    [XmlIgnoreAttribute()]
    private Collection<Certification> _certification;
    
    [XmlElementAttribute("certification")]
    public Collection<Certification> Certification
    {
        get
        {
            return _certification;
        }
        private set
        {
            _certification = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Certification collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool CertificationSpecified
    {
        get
        {
            return (this.Certification.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Certifications" /> class.</para>
    /// </summary>
    public Certifications()
    {
        this._certification = new Collection<Certification>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("glns", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("glns", Namespace="")]
public partial class Glns
{
    
    [XmlIgnoreAttribute()]
    private Collection<int> _gln;
    
    [XmlElementAttribute("gln")]
    public Collection<int> Gln
    {
        get
        {
            return _gln;
        }
        private set
        {
            _gln = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Gln collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool GlnSpecified
    {
        get
        {
            return (this.Gln.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Glns" /> class.</para>
    /// </summary>
    public Glns()
    {
        this._gln = new Collection<int>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("allergen", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("allergen", Namespace="")]
public partial class Allergen
{
    
    [XmlElementAttribute("shortName")]
    public string ShortName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("name")]
    public string Name { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("flag")]
    public sbyte Flag { get; set; }
    
    [XmlElementAttribute("info")]
    public string Info { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("text")]
    public string Text { get; set; }
    
    [XmlElementAttribute("remark")]
    public string Remark { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("nutrient", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("nutrient", Namespace="")]
public partial class Nutrient
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("code")]
    public string Code { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("name")]
    public string Name { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("euName")]
    public string EuName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("unit")]
    public string Unit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("value")]
    public float Value { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("text")]
    public string Text { get; set; }
    
    [XmlElementAttribute("rda")]
    public short Rda { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Rda property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool RdaSpecified { get; set; }
    
    [XmlElementAttribute("rdaPercentage")]
    public float RdaPercentage { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the RdaPercentage property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool RdaPercentageSpecified { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("portionValue")]
    public float PortionValue { get; set; }
    
    [XmlAttributeAttribute("id")]
    public string Id { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("nutrientAnnotation", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("nutrientAnnotation", Namespace="")]
public partial class NutrientAnnotation
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additiveLabel", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additiveLabel", Namespace="")]
public partial class AdditiveLabel
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additiveClass", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additiveClass", Namespace="")]
public partial class AdditiveClass
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public string Id { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additive", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additive", Namespace="")]
public partial class Additive
{
    
    [XmlElementAttribute("additiveClass")]
    public AdditiveClass AdditiveClass { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("additiveName")]
    public string AdditiveName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("additiveNumber")]
    public string AdditiveNumber { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("productInfo", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("productInfo", Namespace="")]
public partial class ProductInfo
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("name")]
    public string Name { get; set; }
    
    [XmlElementAttribute("info")]
    public string Info { get; set; }
    
    [XmlElementAttribute("comment")]
    public string Comment { get; set; }
    
    [XmlElementAttribute("seq")]
    public sbyte Seq { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool SeqSpecified { get; set; }
    
    [XmlElementAttribute("type")]
    public string Type { get; set; }
    
    [XmlAttributeAttribute("id")]
    public int Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("userSpecificInfo", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("userSpecificInfo", Namespace="")]
public partial class UserSpecificInfo
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("type")]
    public string Type { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("header")]
    public string Header { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("text")]
    public string Text { get; set; }
    
    [XmlElementAttribute("seq")]
    public sbyte Seq { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Seq property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool SeqSpecified { get; set; }
    
    [XmlAttributeAttribute("id")]
    public int Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("dietType", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("dietType", Namespace="")]
public partial class DietType
{
    
    [XmlElementAttribute("dietType")]
    public DietType DietTypeProperty { get; set; }
    
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the ImageId property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool ImageIdSpecified { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
    
    [XmlTextAttribute()]
    public string[] Text { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("productCertification", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("productCertification", Namespace="")]
public partial class ProductCertification
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("text")]
    public string Text { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("group")]
    public string Group { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("brand", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("brand", Namespace="")]
public partial class Brand
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("productCategory", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("productCategory", Namespace="")]
public partial class ProductCategory
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("productSubCategory", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("productSubCategory", Namespace="")]
public partial class ProductSubCategory
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("storageType", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("storageType", Namespace="")]
public partial class StorageType
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("preparationInfo", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("preparationInfo", Namespace="")]
public partial class PreparationInfo
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("gvoDeclaration", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("gvoDeclaration", Namespace="")]
public partial class GvoDeclaration
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("unitPack", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("unitPack", Namespace="")]
public partial class UnitPack
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("contentInfo")]
    public string ContentInfo { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("dimension")]
    public string Dimension { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeight")]
    public string GrossWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightApprox")]
    public sbyte GrossWeightApprox { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightUnit")]
    public string GrossWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightValue")]
    public short GrossWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeight")]
    public string NetWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightApprox")]
    public sbyte NetWeightApprox { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightUnit")]
    public string NetWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightValue")]
    public short NetWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeight")]
    public string DrainWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeightUnit")]
    public string DrainWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeightValue")]
    public short DrainWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("packagingWeight")]
    public string PackagingWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("packagingWeightValue")]
    public sbyte PackagingWeightValue { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("tradingUnit", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("tradingUnit", Namespace="")]
public partial class TradingUnit
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("contentInfo")]
    public string ContentInfo { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("dimension")]
    public string Dimension { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("type")]
    public string Type { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeight")]
    public string GrossWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightApprox")]
    public sbyte GrossWeightApprox { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightUnit")]
    public string GrossWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("grossWeightValue")]
    public short GrossWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeight")]
    public string NetWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightApprox")]
    public sbyte NetWeightApprox { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightUnit")]
    public string NetWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("netWeightValue")]
    public short NetWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeight")]
    public string DrainWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeightUnit")]
    public string DrainWeightUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("drainWeightValue")]
    public short DrainWeightValue { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("packagingWeight")]
    public string PackagingWeight { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("packagingWeightValue")]
    public sbyte PackagingWeightValue { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("palette", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("palette", Namespace="")]
public partial class Palette
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("dimension")]
    public string Dimension { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("handling")]
    public string Handling { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("tiersPerPalette")]
    public sbyte TiersPerPalette { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("type")]
    public string Type { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("unitsPerPalette")]
    public sbyte UnitsPerPalette { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("unitsPerTier")]
    public sbyte UnitsPerTier { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("totalWeightKG")]
    public string TotalWeightKg { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("commonInfo", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("commonInfo", Namespace="")]
public partial class CommonInfo
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("ingredients", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("ingredients", Namespace="")]
public partial class Ingredients
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("storageInstruction", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("storageInstruction", Namespace="")]
public partial class StorageInstruction
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("techData", Namespace="")]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("techData", Namespace="")]
public partial class TechData
{
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets the text value.</para>
    /// </summary>
    [XmlTextAttribute()]
    public string Value { get; set; }
    
    [XmlAttributeAttribute("id")]
    public sbyte Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("dataProducer", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("dataProducer", Namespace="")]
public partial class DataProducer
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("producerName")]
    public string ProducerName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("producerName2")]
    public string ProducerName2 { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("shortName")]
    public string ShortName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("shopURL")]
    public string ShopUrl { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("producerId")]
    public short ProducerId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactFirstname")]
    public string ContactFirstname { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactName")]
    public string ContactName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactSalutation")]
    public string ContactSalutation { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactFunction")]
    public string ContactFunction { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("address")]
    public Address Address { get; set; }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("manufacturer", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("manufacturer", Namespace="")]
public partial class Manufacturer
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerName")]
    public string ManufacturerName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerName2")]
    public string ManufacturerName2 { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerShortName")]
    public string ManufacturerShortName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("shopURL")]
    public string ShopUrl { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerId")]
    public short ManufacturerId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactFirstname")]
    public string ContactFirstname { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactName")]
    public string ContactName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactSalutation")]
    public string ContactSalutation { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("contactFunction")]
    public string ContactFunction { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("address")]
    public Address Address { get; set; }
    
    [XmlIgnoreAttribute()]
    private Collection<Certification> _certifications;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("certifications")]
    [XmlArrayItemAttribute("certification")]
    public Collection<Certification> Certifications
    {
        get
        {
            return _certifications;
        }
        private set
        {
            _certifications = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Manufacturer" /> class.</para>
    /// </summary>
    public Manufacturer()
    {
        this._certifications = new Collection<Certification>();
        this._glns = new Collection<int>();
    }
    
    [XmlIgnoreAttribute()]
    private Collection<int> _glns;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("glns")]
    [XmlArrayItemAttribute("gln")]
    public Collection<int> Glns
    {
        get
        {
            return _glns;
        }
        private set
        {
            _glns = value;
        }
    }
    
    [XmlAttributeAttribute("id")]
    public short Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("allergens", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("allergens", Namespace="")]
public partial class Allergens
{
    
    [XmlIgnoreAttribute()]
    private Collection<Allergen> _allergen;
    
    [XmlElementAttribute("allergen")]
    public Collection<Allergen> Allergen
    {
        get
        {
            return _allergen;
        }
        private set
        {
            _allergen = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Allergen collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool AllergenSpecified
    {
        get
        {
            return (this.Allergen.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Allergens" /> class.</para>
    /// </summary>
    public Allergens()
    {
        this._allergen = new Collection<Allergen>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("nutrients", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("nutrients", Namespace="")]
public partial class Nutrients
{
    
    [XmlIgnoreAttribute()]
    private Collection<Nutrient> _nutrient;
    
    [XmlElementAttribute("nutrient")]
    public Collection<Nutrient> Nutrient
    {
        get
        {
            return _nutrient;
        }
        private set
        {
            _nutrient = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Nutrient collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool NutrientSpecified
    {
        get
        {
            return (this.Nutrient.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Nutrients" /> class.</para>
    /// </summary>
    public Nutrients()
    {
        this._nutrient = new Collection<Nutrient>();
    }
    
    [RequiredAttribute()]
    [XmlElementAttribute("nutrientAnnotation")]
    public NutrientAnnotation NutrientAnnotation { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additiveLabels", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additiveLabels", Namespace="")]
public partial class AdditiveLabels
{
    
    [XmlIgnoreAttribute()]
    private Collection<AdditiveLabel> _additiveLabel;
    
    [XmlElementAttribute("additiveLabel")]
    public Collection<AdditiveLabel> AdditiveLabel
    {
        get
        {
            return _additiveLabel;
        }
        private set
        {
            _additiveLabel = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the AdditiveLabel collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool AdditiveLabelSpecified
    {
        get
        {
            return (this.AdditiveLabel.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="AdditiveLabels" /> class.</para>
    /// </summary>
    public AdditiveLabels()
    {
        this._additiveLabel = new Collection<AdditiveLabel>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additives", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additives", Namespace="")]
public partial class Additives
{
    
    [XmlIgnoreAttribute()]
    private Collection<Additive> _additive;
    
    [XmlElementAttribute("additive")]
    public Collection<Additive> Additive
    {
        get
        {
            return _additive;
        }
        private set
        {
            _additive = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Additive collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool AdditiveSpecified
    {
        get
        {
            return (this.Additive.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Additives" /> class.</para>
    /// </summary>
    public Additives()
    {
        this._additive = new Collection<Additive>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("additionalProductInfos", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("additionalProductInfos", Namespace="")]
public partial class AdditionalProductInfos
{
    
    [XmlIgnoreAttribute()]
    private Collection<ProductInfo> _productInfo;
    
    [XmlElementAttribute("productInfo")]
    public Collection<ProductInfo> ProductInfo
    {
        get
        {
            return _productInfo;
        }
        private set
        {
            _productInfo = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the ProductInfo collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool ProductInfoSpecified
    {
        get
        {
            return (this.ProductInfo.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="AdditionalProductInfos" /> class.</para>
    /// </summary>
    public AdditionalProductInfos()
    {
        this._productInfo = new Collection<ProductInfo>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("userSpecificInfos", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("userSpecificInfos", Namespace="")]
public partial class UserSpecificInfos
{
    
    [XmlIgnoreAttribute()]
    private Collection<UserSpecificInfo> _userSpecificInfo;
    
    [XmlElementAttribute("userSpecificInfo")]
    public Collection<UserSpecificInfo> UserSpecificInfo
    {
        get
        {
            return _userSpecificInfo;
        }
        private set
        {
            _userSpecificInfo = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the UserSpecificInfo collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool UserSpecificInfoSpecified
    {
        get
        {
            return (this.UserSpecificInfo.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="UserSpecificInfos" /> class.</para>
    /// </summary>
    public UserSpecificInfos()
    {
        this._userSpecificInfo = new Collection<UserSpecificInfo>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("dietTypes", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("dietTypes", Namespace="")]
public partial class DietTypes
{
    
    [XmlIgnoreAttribute()]
    private Collection<DietType> _dietType;
    
    [XmlElementAttribute("dietType")]
    public Collection<DietType> DietType
    {
        get
        {
            return _dietType;
        }
        private set
        {
            _dietType = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the DietType collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool DietTypeSpecified
    {
        get
        {
            return (this.DietType.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="DietTypes" /> class.</para>
    /// </summary>
    public DietTypes()
    {
        this._dietType = new Collection<DietType>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("allergens2", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("allergens2", Namespace="")]
public partial class Allergens2
{
    
    [XmlIgnoreAttribute()]
    private Collection<Allergen> _allergen;
    
    [XmlElementAttribute("allergen")]
    public Collection<Allergen> Allergen
    {
        get
        {
            return _allergen;
        }
        private set
        {
            _allergen = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Allergen collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool AllergenSpecified
    {
        get
        {
            return (this.Allergen.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Allergens2" /> class.</para>
    /// </summary>
    public Allergens2()
    {
        this._allergen = new Collection<Allergen>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("productCertifications", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("productCertifications", Namespace="")]
public partial class ProductCertifications
{
    
    [XmlIgnoreAttribute()]
    private Collection<ProductCertification> _productCertification;
    
    [XmlElementAttribute("productCertification")]
    public Collection<ProductCertification> ProductCertification
    {
        get
        {
            return _productCertification;
        }
        private set
        {
            _productCertification = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the ProductCertification collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool ProductCertificationSpecified
    {
        get
        {
            return (this.ProductCertification.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="ProductCertifications" /> class.</para>
    /// </summary>
    public ProductCertifications()
    {
        this._productCertification = new Collection<ProductCertification>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("gtins", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("gtins", Namespace="")]
public partial class Gtins
{
    
    [XmlIgnoreAttribute()]
    private Collection<long> _gtin;
    
    [XmlElementAttribute("gtin")]
    public Collection<long> Gtin
    {
        get
        {
            return _gtin;
        }
        private set
        {
            _gtin = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Gets a value indicating whether the Gtin collection is empty.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool GtinSpecified
    {
        get
        {
            return (this.Gtin.Count != 0);
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Gtins" /> class.</para>
    /// </summary>
    public Gtins()
    {
        this._gtin = new Collection<long>();
    }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("supplierData", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("supplierData", Namespace="")]
public partial class SupplierData
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("supplierAID")]
    public short SupplierAid { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("supplierAID2")]
    public string SupplierAid2 { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("product", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("product", Namespace="")]
public partial class Product
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerAID")]
    public string ManufacturerAid { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("name")]
    public string Name { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("identification")]
    public string Identification { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("brand")]
    public Brand Brand { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("actualisationDate")]
    public string ActualisationDate { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("updateDate")]
    public string UpdateDate { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("expirationDate")]
    public string ExpirationDate { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("euFoodInfoCompliant")]
    public sbyte EuFoodInfoCompliant { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("isReducedInfo")]
    public sbyte IsReducedInfo { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("imageId")]
    public int ImageId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("brandImageId")]
    public int BrandImageId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("productCategory")]
    public ProductCategory ProductCategory { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("productSubCategory")]
    public ProductSubCategory ProductSubCategory { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("gtin")]
    public long Gtin { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("blsAID")]
    public string BlsAid { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("blsName")]
    public string BlsName { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("nutrientReferenceUnit")]
    public string NutrientReferenceUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("portionSize")]
    public sbyte PortionSize { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("usedBlsNutrients")]
    public sbyte UsedBlsNutrients { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("productId")]
    public int ProductId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("storageType")]
    public StorageType StorageType { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("minShelfLife")]
    public string MinShelfLife { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("remainingLife")]
    public string RemainingLife { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("isDirectDistribution")]
    public sbyte IsDirectDistribution { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("isSpecializedWholesaleTrade")]
    public sbyte IsSpecializedWholesaleTrade { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("isOnlineShopping")]
    public sbyte IsOnlineShopping { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("isCashnCarry")]
    public sbyte IsCashnCarry { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerProductCategory")]
    public string ManufacturerProductCategory { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturerProductSubCategory")]
    public string ManufacturerProductSubCategory { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("infoURL")]
    public string InfoUrl { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("servingImgId")]
    public int ServingImgId { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("unitPackEAN")]
    public long UnitPackEan { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("singleUnitsPerTradingUnit")]
    public sbyte SingleUnitsPerTradingUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("creationDate")]
    public string CreationDate { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("preparationInfo")]
    public PreparationInfo PreparationInfo { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("gvoDeclaration")]
    public GvoDeclaration GvoDeclaration { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("nutrientAnnotation")]
    public NutrientAnnotation NutrientAnnotation { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("unitPack")]
    public UnitPack UnitPack { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("tradingUnit")]
    public TradingUnit TradingUnit { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("palette")]
    public Palette Palette { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("commonInfo")]
    public CommonInfo CommonInfo { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("ingredients")]
    public Ingredients Ingredients { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("storageInstruction")]
    public StorageInstruction StorageInstruction { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("techData")]
    public TechData TechData { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("dataProducer")]
    public DataProducer DataProducer { get; set; }
    
    [RequiredAttribute()]
    [XmlElementAttribute("manufacturer")]
    public Manufacturer Manufacturer { get; set; }
    
    [XmlIgnoreAttribute()]
    private Collection<Allergen> _allergens;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("allergens")]
    [XmlArrayItemAttribute("allergen")]
    public Collection<Allergen> Allergens
    {
        get
        {
            return _allergens;
        }
        private set
        {
            _allergens = value;
        }
    }
    
    /// <summary>
    /// <para xml:lang="en">Initializes a new instance of the <see cref="Product" /> class.</para>
    /// </summary>
    public Product()
    {
        this._allergens = new Collection<Allergen>();
        this._additiveLabels = new Collection<AdditiveLabel>();
        this._additives = new Collection<Additive>();
        this._additionalProductInfos = new Collection<ProductInfo>();
        this._userSpecificInfos = new Collection<UserSpecificInfo>();
        this._dietTypes = new Collection<DietType>();
        this._allergens2 = new Collection<Allergen>();
        this._productCertifications = new Collection<ProductCertification>();
        this._gtins = new Collection<long>();
    }
    
    [RequiredAttribute()]
    [XmlElementAttribute("nutrients")]
    public Nutrients Nutrients { get; set; }
    
    [XmlIgnoreAttribute()]
    private Collection<AdditiveLabel> _additiveLabels;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("additiveLabels")]
    [XmlArrayItemAttribute("additiveLabel")]
    public Collection<AdditiveLabel> AdditiveLabels
    {
        get
        {
            return _additiveLabels;
        }
        private set
        {
            _additiveLabels = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<Additive> _additives;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("additives")]
    [XmlArrayItemAttribute("additive")]
    public Collection<Additive> Additives
    {
        get
        {
            return _additives;
        }
        private set
        {
            _additives = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<ProductInfo> _additionalProductInfos;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("additionalProductInfos")]
    [XmlArrayItemAttribute("productInfo")]
    public Collection<ProductInfo> AdditionalProductInfos
    {
        get
        {
            return _additionalProductInfos;
        }
        private set
        {
            _additionalProductInfos = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<UserSpecificInfo> _userSpecificInfos;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("userSpecificInfos")]
    [XmlArrayItemAttribute("userSpecificInfo")]
    public Collection<UserSpecificInfo> UserSpecificInfos
    {
        get
        {
            return _userSpecificInfos;
        }
        private set
        {
            _userSpecificInfos = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<DietType> _dietTypes;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("dietTypes")]
    [XmlArrayItemAttribute("dietType")]
    public Collection<DietType> DietTypes
    {
        get
        {
            return _dietTypes;
        }
        private set
        {
            _dietTypes = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<Allergen> _allergens2;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("allergens2")]
    [XmlArrayItemAttribute("allergen")]
    public Collection<Allergen> Allergens2
    {
        get
        {
            return _allergens2;
        }
        private set
        {
            _allergens2 = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<ProductCertification> _productCertifications;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("productCertifications")]
    [XmlArrayItemAttribute("productCertification")]
    public Collection<ProductCertification> ProductCertifications
    {
        get
        {
            return _productCertifications;
        }
        private set
        {
            _productCertifications = value;
        }
    }
    
    [XmlIgnoreAttribute()]
    private Collection<long> _gtins;
    
    [RequiredAttribute()]
    [XmlArrayAttribute("gtins")]
    [XmlArrayItemAttribute("gtin")]
    public Collection<long> Gtins
    {
        get
        {
            return _gtins;
        }
        private set
        {
            _gtins = value;
        }
    }
    
    [RequiredAttribute()]
    [XmlElementAttribute("supplierData")]
    public SupplierData SupplierData { get; set; }
    
    [XmlAttributeAttribute("id")]
    public int Id { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Id property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool IdSpecified { get; set; }
}

[GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
[SerializableAttribute()]
[XmlTypeAttribute("prins", Namespace="", AnonymousType=true)]
[DebuggerStepThroughAttribute()]
[DesignerCategoryAttribute("code")]
[XmlRootAttribute("prins", Namespace="")]
public partial class Prins
{
    
    [RequiredAttribute()]
    [XmlElementAttribute("product")]
    public Product Product { get; set; }
    
    [XmlAttributeAttribute("version")]
    public sbyte Version { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Version property is specified.</para>
    /// </summary>
    [XmlIgnoreAttribute()]
    public bool VersionSpecified { get; set; }
    
    [XmlAttributeAttribute("created")]
    public string Created { get; set; }
}
