
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace GeneratedPrinsParserTest;

using Prins = Prins.Prins;


/*
 * copied from here https://learn.microsoft.com/en-us/dotnet/standard/data/xml/inferring-schemas-from-xml-documents
 * 
XmlReader reader = XmlReader.Create("item1.xml");
XmlReader reader1 = XmlReader.Create("item2.xml");
XmlSchemaSet schemaSet = new XmlSchemaSet();
XmlSchemaInference inference = new XmlSchemaInference();
schemaSet = inference.InferSchema(reader);

// Display the inferred schema.
Console.WriteLine("Original schema:\n");
foreach (XmlSchema schema in schemaSet.Schemas("http://www.contoso.com/items"))
{
    schema.Write(Console.Out);
}

// Use the additional data in item2.xml to refine the original schema.
schemaSet = inference.InferSchema(reader1, schemaSet);

// Display the refined schema.
Console.WriteLine("\n\nRefined schema:\n");
foreach (XmlSchema schema in schemaSet.Schemas("http://www.contoso.com/items")) {
    schema.Write(Console.Out);
}
*/

internal class Program
{

    // Model.cs is generated by https://json2csharp.com/code-converters/xml-to-csharp
    // NOTE: this was generated from testdata.xml (whithout schema) and needed to be fixed to parse
    // the "testdata.xml" without error

    // Prins.cs is generated by "XmlSchemaClassGenerator.Console -cn -n Prins testdata.xsd" (from schema)
    // NOTE: this can parse the testdata.xml without errors out of the box

    // testdata.xsd is generated by System.Xml.Schema.XmlSchemaInference as seen below


    static void Main(string[] args)
    {
        /*
        var reader = XmlReader.Create("testdata.xml");
        var schemaWriter = XmlWriter.Create("testdata.xsd");

        var inference = new XmlSchemaInference();
        var schemaSet = inference.InferSchema(reader);

        foreach (XmlSchema schema in schemaSet.Schemas()) {
            schema.Write(schemaWriter);
        }
        */

        XmlSerializer serializer = new XmlSerializer(typeof(Prins));

        var xml = File.ReadAllText("testdata.xml");

        using (StringReader reader = new StringReader(xml))
        {
            var test = (Prins)serializer.Deserialize(reader);
        }

    }
}